version: "3.7"

services:
  ng:
    build:
      context: ./angular
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./angular/:/app/
    ports:
      - 4200:4200
      - 8888:8888
    command: >
      bash -c "
        npm install &&
        npm run start"
