#!/usr/bin/env python
import sys
import os

if len(sys.argv) > 1:
    branch = sys.argv[1]
else:
    branch = 'master'

# UPDATE
os.system('git fetch')
os.system('git checkout {} && git rebase origin/{}'.format(branch, branch))
os.system('git submodule update --recursive --remote')

repositories = [
    'angular',
    'react',
]
for repository in repositories:
    os.system('cd {} && git checkout {} && git rebase origin/{}'.format(repository, branch, branch))
